### ISSUE TITLE
Convert Child Themes Lesson Plan

### ISSUE THREAD

**Issue by JulieKuehl** [wptrainingteam/child-themes#4]
Convert Lesson Plan to GitHub

- [x]  copy and paste from Make site
- [x]  clean up the Markdown
- [x]  download the old images
- [x]  upload the images into GitHub
- [x]  swap out the image links

**Comment by jsmcintyre25** [comment]
### Convert Child Themes to GitHub

- [x] copy and paste from Make site
- [x] clean up the Markdown
- [x] download the old images
- [x] upload the images into GitHub
- [x] swap out the image links

**Comment by JulieKuehl** [comment]
Thanks Josh! It looks like if I add that to the initial comment, the tasks show up on the project boards.
